# Generated by Django 4.2.30 on 2026-08-16 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_destination_latitude_destination_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationVisitPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('days', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_packages', to='destinations.destination')),
            ],
            options={
                'ordering': ('days', 'name'),
            },
        ),
    ]
