# Generated by Django 4.2.30 on 2026-08-19 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'ordering': ('-updated_at', '-id')},
        ),
    ]
